---
- hosts: local
  gather_facts: false
  vars_files:
    - vars.yml
    - vault.yml

  tasks:
  - name: Configure GitHub SSH key
    include_tasks: tasks/github.yml
    tags:
      - github

  - name: Include dotfiles
    include_tasks: tasks/dotfiles.yml
    tags:
      - links
  - name: Install homebrew packages and such
    include_tasks: tasks/brew.yml
    tags:
      - homebrew
      - casks
  - name: Setup Zsh
    include_tasks: tasks/zsh.yml

  - include_role:
      name: ruby
    tags:
      - ruby
  - include_role:
      name: javascript
    tags:
      - fnm
      - npm
  - include_role:
      name: docker
    tags: docker
  - include_role:
      name: mongo
  - include_role:
      name: java
    tags:
      - java
  - include_role:
      name: python
    tags:
      - python
  - include_role:
      name: go
    tags:
      - go
  - include_role:
      name: rust
    tags:
      - rust
  - include_role:
      name: neovim
    tags:
      - neovim
