---
- hosts: local
  gather_facts: false
  vars:
    full_name:  "{{ lookup('env', 'NAME') }}"
    email: "{{ lookup('env', 'EMAIL') }}"
    user: "{{ lookup('env', 'USER') }}"
    github_key: "{{ lookup('env', 'GITHUB_API_TOKEN') }}"

  tasks:
  - name: generate an shh key
    command: ssh-keygen -t rsa -b 4096 -C {{ email }} -N "" -f ~/.ssh/id_rsa
    args:
      creates: ~/.ssh/id_rsa

  - name: save public key to variable
    set_fact:
      public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: getup global git config
    git_config:
      name: user.name
      scope: global
      value: "{{ full_name }}"

  - name:
    git_config:
      name: core.editor
      scope: global
      value: /usr/bin/vim

  - name: list out global git config
    git_config:
      list_all: yes
      scope: global

  - name: add public key to github
    shell: |
      curl -H "Content-Type: application/json"\
           -H "Authorization: token $GITHUB_API_TOKEN"\
           --data '{"title":"mac-ansible-token", "key":"'"{{ public_key }}"'"}'\
           https://api.github.com/user/keys


  - include: tasks/zsh.yml
  - include: tasks/brew.yml
  - include: tasks/dotfiles.yml
