---
- hosts: local
  vars: 
    name:  "{{ lookup('env', 'NAME') }}"
    email: "{{ lookup('env', 'EMAIL') }}"
    github_key: "{{ lookup('env', 'GITHUB_API_TOKEN') }}"
    public_key: "{{ lookup('env', 'PUBLIC_KEY') }}"

  tasks:
  - name: generate an shh key
    command: ssh-keygen -t rsa -b 4096 -C {{ email }} -N "" -f ~/.ssh/id_rsa
    args:
      creates: ~/.ssh/id_rsa 

  - name: getup global git config
    git_config:
      name: user.name
      scope: global
      value: "{{ name }}"
  
  - name: list out global git config
    git_config:
      list_all: yes
      scope: global

  - name: add public key to github
    shell: |
      curl -H "Content-Type: application/json"\
           -H "Authorization: token $GITHUB_API_TOKEN"\
           --data '{"title":"mac-ansible-token", "key":"'"$PUBLIC_KEY"'"}'\
           https://api.github.com/user/keys
