---
- name: update homebrew
  command: "brew update"
  register: result
  changed_when: "result.stdout != 'Already up-to-date.'"
  tags:
    - homebrew

- name: tap homebrew cask fonts
  homebrew_tap:
    name: homebrew/cask-fonts
  tags:
    - casks
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - iterm2
    - google-chrome
    - firefox
    - dropbox
    - 1password
    - alfred
    - spotify
    - intellij-idea
    - visual-studio-code
    - slack
    - whatsapp
    - font-fira-code
    - font-dejavu-sans-mono-nerd-font
    - zoom
    - keybase
  tags:
    - casks
    - homebrew

- name: tap heroku repository
  homebrew_tap:
    name: heroku/brew
  tags:
    - casks
    - homebrew

- name: install vagrant casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox
    - vagrant
    - vagrant-manager
  tags:
    - casks
    - vagrant

- name: install chef
  homebrew:
    name: chef/chef/inspec
    state: present
  tags:
    - packages
    - homebrew
    - inspec

- name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    # cloud vendors
    - awscli
    - aws-vault
    - aws-iam-authenticator
    - eksctl
    - chamber

    # cloud dev
    - colima
    - minikube
    - kubernetes-cli
    - kubectx
    - krew
    - sonobuoy
    - skaffold
    - helm
    - stern
    - txn2/tap/kubefwd
    - 1password/tap/1password-cli
    - kubeval
    - terraform
    - terraform-docs
    - tflint
    - istioctl
    - hadolint
    - yamllint
    - pulumi
    - opa

    # dev tools
    - vim
    - nvim
    - starship
    - fzf
    - tmux
    - exercism
    - tree
    - antigen
    - hub
    - httpie

    - circleci
    - vault
    - jq
    - watchman
    - autojump
    - ag
    - watch
    - gsed
    - gnupg
    - cosign
    - talisman
    - hostess
    - lima
    - pre-commit
    - ripgrep

  tags:
    - packages
    - homebrew

- name: install fzf keybindings
  shell: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc
  tags:
   - packages
   - homebrew

- name: create workspace with personal directory
  file:
    path: ~/workspace/personal
    state: directory
  tags:
    - exercism
    - homebrew

- name: create workspace with work directory
  file:
    path: ~/workspace/work
    state: directory
  tags:
    - exercism
    - homebrew

- name: configure exercism api key
  command: exercism configure --token={{ exercism_api_key }} --workspace=~/workspace/personal/exercism
  tags:
    - exercism
