---
- name: update homebrew
  command: "brew update"
  register: result
  changed_when: "result.stdout != 'Already up-to-date.'"

- name: install homebrew casks 
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - iterm2
    - google-chrome
    - dropbox
    - 1password
    - alfred
