---
- name: update homebrew
  command: "brew update"
  register: result
  changed_when: "result.stdout != 'Already up-to-date.'"

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - iterm2
    - google-chrome
    - dropbox
    - 1password
    - alfred
    - spectacle
    - spotify
    - virtualbox
    - vagrant
    - vagrant-manager
    - intellij-idea
    - visual-studio-code
    - postman
    - slack
    - whatsapp
  tags:
    - casks

- name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - fzf
    - tmux
    - exercism
    - awscli
    - tree
    - antigen
    - hub
    - httpie
    - vim
  tags:
    - packages

- name: install fzf keybindings
  shell: $(brew --prefix)/opt/fzf/install --all
  tags:
   - packages

- name: configure exercism api key
  command: exercism configure --key={{ exercism_api_key }} --dir=~/projects/exercism
