---
  - name: update homebrew
    command: "brew update"
    register: result
    changed_when: "result.stdout != 'Already up-to-date.'"

  - name: install iterm
    homebrew_cask:
      name: iterm2
      state: present
