---
- name: update homebrew
  command: "brew update"
  register: result
  changed_when: "result.stdout != 'Already up-to-date.'"
  tags:
    - homebrew

- name: tap homebrew cask fonts
  homebrew_tap:
    name: homebrew/cask-fonts
  tags:
    - casks
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - iterm2
    - google-chrome
    - dropbox
    - 1password
    - alfred
    - spectacle
    - spotify
    - intellij-idea
    - webstorm
    - visual-studio-code
    - postman
    - slack
    - whatsapp
    - flux
    - microsoft-teams
    - font-fira-code
  tags:
    - casks
    - homebrew

- name: tap heroku repository
  homebrew_tap:
    name: heroku/brew
  tags:
    - casks
    - homebrew

- name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - fzf
    - tmux
    - exercism
    - awscli
    - tree
    - antigen
    - hub
    - httpie
    - vim
    - elm
    - python@2
    - heroku
  tags:
    - packages
    - homebrew

- name: install fzf keybindings
  shell: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc
  tags:
   - packages
   - homebrew

- name: create workspace with personal directory
  file:
    path: ~/workspace/personal
    state: directory
  tags:
    - exercism
    - homebrew


- name: configure exercism api key
  command: exercism configure --token={{ exercism_api_key }} --workspace=~/workspace/personal/exercism
  tags:
    - exercism
