---
- name: update homebrew
  command: "brew update"
  register: result
  changed_when: "result.stdout != 'Already up-to-date.'"
  tags:
    - homebrew

- name: install personal homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - alfred
    - discord
    - whatsapp
    - zoom
  when: install_personal_casks | bool
  tags:
    - casks
    - personal
    - homebrew

- name: install vagrant homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox
    - vagrant
    - vagrant-manager
  when: install_vagrant_casks | bool
  tags:
    - casks
    - vagrant
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - 1password
    - 1password-cli
    - firefox
    - font-dejavu-sans-mono-nerd-font
    - font-fira-code
    - google-chrome
    - intellij-idea-ce
    - iterm2
    - keybase
    - obsidian
    # .net? - session-manager-plugin
    - slack
    - spotify
    #- temurin17
    #- temurin@17
    - visual-studio-code
    #- vmware-fusion
    - wireshark
  tags:
    - casks
    - homebrew

- name: tap heroku repository
  homebrew_tap:
    name: heroku/brew
  tags:
    - casks
    - homebrew

- name: tap hashicorp repository
  homebrew_tap:
    name: hashicorp/tap
  tags:
    - packages
    - homebrew

- name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    # cloud vendors
    - awscli
    - aws-vault
    - eksctl

    # cloud dev
    - colima
    - minikube
    - kubernetes-cli
    - kubelogin
    - kubectx
    - krew
    - skaffold
    - helm
    - stern
    - 1password-cli
    - tenv
    - hashicorp/tap/vault
    #- terraform-docs
    #- tflint # was removed from homebrew casks
    - istioctl
    - hadolint
    - yamllint
    - pulumi
    - opa

    # dev tools
    - vim
    - nvim
    - starship
    - fzf
    - tmux
    - exercism
    - tree
    - antigen
    - hub
    - libpq # postgres tools

    - circleci
    - jq
    - watchman
    - autojump
    - ag
    - watch
    - gsed
    - gnupg
    - cosign
    - talisman
    - hostess
    - lima
    - pre-commit
    - ripgrep
    # ai
    - dolt

  tags:
    - packages
    - homebrew

- name: install fzf keybindings
  shell: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc
  tags:
   - packages
   - homebrew

- name: create workspace with personal directory
  file:
    path: ~/workspace/personal
    state: directory
  tags:
    - exercism
    - homebrew

- name: create workspace with work directory
  file:
    path: ~/workspace/work
    state: directory
  tags:
    - exercism
    - homebrew

- name: configure exercism api key
  command: exercism configure --token={{ exercism_api_key }} --workspace=~/workspace/personal/exercism
  tags:
    - exercism
