---
- name: update homebrew
  command: "brew update"
  register: result
  changed_when: "result.stdout != 'Already up-to-date.'"
  tags:
    - homebrew

- name: tap homebrew cask fonts
  homebrew_tap:
    name: homebrew/cask-fonts
  tags:
    - casks
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - iterm2
    - google-chrome
    - firefox
    - dropbox
    - 1password
    - alfred
    - spectacle
    - spotify
    - intellij-idea
    - webstorm
    - visual-studio-code
    - postman
    - slack
    - whatsapp
    - flux
    - microsoft-teams
    - font-fira-code
    - font-dejavu-sans-mono-nerd-font
    - zoomus
    - starship
    - aws-vault
  tags:
    - casks
    - homebrew

- name: tap heroku repository
  homebrew_tap:
    name: heroku/brew
  tags:
    - casks
    - homebrew

- name: install vagrant casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox
    - vagrant
    - vagrant-manager
  tags:
    - casks
    - vagrant

- name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - stern
    - fzf
    - tmux
    - exercism
    - awscli
    - aws-iam-authenticator
    - tree
    - antigen
    - hub
    - httpie
    - vim
    - elm
    #- python@2
    - heroku
    - postgres
    - circleci
    - hadolint
    - kubernetes-cli
    - terraform
    - vault
    - yamllint
    - kubectx
    - jq
    - watchman
    - chef/chec/inspec
    - chamber
    - kubernetes-helm

  tags:
    - packages
    - homebrew

- name: install fzf keybindings
  shell: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc
  tags:
   - packages
   - homebrew

- name: create workspace with personal directory
  file:
    path: ~/workspace/personal
    state: directory
  tags:
    - exercism
    - homebrew

- name: create workspace with work directory
  file:
    path: ~/workspace/work
    state: directory
  tags:
    - exercism
    - homebrew

- name: configure exercism api key
  command: exercism configure --token={{ exercism_api_key }} --workspace=~/workspace/personal/exercism
  tags:
    - exercism
