---

- name: clone down dotfiles from github
  git:
    repo: git@github.com:saylerb/dotfiles.git
    dest: ~/dotfiles

- name: symlink .vimrc to home directory
  file:
    src: ~/dotfiles/.vimrc
    dest: ~/.vimrc
    mode: 0755
    state: link

- name: download vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: install plugins
  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  ignore_errors: yes

- name: Run PluginClean
  shell: vim '+PluginClean!' +qall

- name: download patched powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    depth: 1
    dest: ~/fonts
  register: fonts_result

- name: install the fonts
  command: ./install.sh
  args:
    chdir: ~/fonts
  when: fonts_result|success

