---

- name: clone down dotfiles from github
  git:
    repo: git@github.com:saylerb/dotfiles.git
    dest: ~/dotfiles

- name: symlink dotfiles to home directory
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    mode: 0755
    state: link
  with_items:
    - .vimrc
    - .tmux.conf
    - .bash_profile
    - .ruby-version

- name: download vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: install plugins
  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  ignore_errors: yes

- name: Run PluginClean
  shell: vim '+PluginClean!' +qall

- name: download patched powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    depth: 1
    dest: ~/fonts
  register: fonts_download

- name: check if fonts are already installed
  find:
    paths: ~/Library/Fonts
    patterns: "*.ttf"
  register: font_files

- name: install the fonts
  command: ./install.sh
  args:
    chdir: ~/fonts
  when:
    - font_files.matched|int == 0
    - fonts_download|success

- name: download iterm2 color profile
  get_url:
    url: https://raw.githubusercontent.com/morhetz/gruvbox-contrib/master/iterm2/gruvbox-dark.itermcolors
    dest: ~/Downloads/
