---

- name: install nvm and use to install node
  include: nvm.yml
  tags:
    - nvm

- name: install yarn via brew excluding node
  homebrew:
    name: yarn
    state: present
  tags:
    - nvm
    - yarn

- name: install global npm packages
  include: npm.yml
  tags:
    - npm
