---
- name: get npm executable location
  shell: |
    eval "$(fnm env --shell bash)"
    fnm use lts-latest
    which npm
  args:
    executable: /bin/bash
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
  register: fnm_executable
  tags:
    - npm

- name: install global packages
  npm:
    name: "{{ item }}"
    global: yes
    executable: "{{ fnm_executable.stdout_lines | last }}"
  with_items:
    - prettier
    - git-mob
    - "@openai/codex"
  tags:
    - npm
