---
- name: get npm executable location
  shell: . ./nvm.sh && nvm use --lts --silent && which npm
  args:
    chdir: "~/.config/nvm"
  register: nvm_executable
  tags:
    - npm

- name: install global packages
  npm: 
    name: "{{ item }}"
    global: yes
    executable: "{{ nvm_executable.stdout }}"
  with_items:
    - prettier
    - git-mob
    - "@openai/codex"
  tags:
    - npm
