---

- name: install global packages
  npm: 
    name: "{{ item }}"
    global: yes
  with_items:
    - gatsby-cli
    - canvas-sketch-cli
    - elm-format
    - create-elm-app
    - prettier
  tags: 
    - npm
