---

- name: check .nvm dir exists
  stat:
    path: ~/.config/nvm
  register: nvm_check
  tags:
    - nvm

- name: clone down the nvm repo
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.config/nvm
    update: no
  when: not nvm_check.stat.exists
  tags:
    - nvm

- name: check .nvm dir exists
  stat:
    path: ~/.config/nvm
  register: nvm_check
  tags:
    - nvm

- set_fact:
    nvm_dir: "{{ nvm_check.stat.path }}"
  tags:
    - nvm

- name: get latest tag name
  shell: "git describe --abbrev=0 --tags --match 'v[0-9]*' $(git rev-list --tags --max-count=1)"
  args:
    chdir: "{{ nvm_dir }}"
  register: latest_tag
  tags:
    - nvm

- name: checkout latest nvm tag
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ nvm_dir }}"
    version: "{{ latest_tag.stdout }}"
  when: not nvm_check.stat.exists
  tags:
    - nvm

- name: install node LTS
  shell: . ./nvm.sh && nvm install --lts
  args:
    chdir: "{{ nvm_dir }}"
  tags:
    - nvm

- name: update npm
  shell: . ./nvm.sh && npm install -g npm
  args:
    chdir: "{{ nvm_dir }}"
  tags:
    - nvm
