---

- name: untap caskroom so we can install adoptopenjdk
  homebrew_tap:
    name: caskroom/versions
    state: absent
  tags: java

- name: tap adoptopenjdk repository
  homebrew_tap:
    name: adoptopenjdk/openjdk
  tags: java

- name: install adoptopenjdk8
  homebrew_cask:
    name: adoptopenjdk8

- name: tap caskroom so we can install pre-built binaries
  homebrew_tap:
    name: caskroom/versions
  tags: java

- name: install lastest oracle java JDK
  homebrew_cask:
    name: java
    state: present
  tags: java

- name: install java homebrew packages
  homebrew:
    name: gradle
    state: present
  tags: java

