---

- name: tap caskroom so we can install pre-built binaries
  shell: brew tap caskroom/versions
  tags: java

- name: install java cask
  homebrew_cask:
    name: java
    state: present
  tags: java

- name: install java homebrew packages
  homebrew:
    name: gradle
    state: present
  tags: java

