---

- name: install docker
  homebrew:
    name: docker
    state: present
  tags:
    - docker

- name: install docker-buildx
  homebrew:
    name: docker-buildx
    state: present
  tags:
    - docker

- name: install docker-compose
  homebrew:
    name: docker-compose
    state: present
  tags:
    - docker

- name: ensure jq is intalled
  homebrew:
    name: jq
    state: present
  tags:
    - docker

- name: ensure docker config directory exists
  file:
    path: ~/.docker
    state: directory
    mode: '0755'
  tags:
    - docker

- name: create initial docker config if not exists
  copy:
    content: "{}"
    dest: ~/.docker/config.json
    force: no
    mode: '0644'
  tags:
    - docker

- name: configure docker cli plugins directory
  shell: |
    cp ~/.docker/config.json ~/.docker/config.json.bak
    jq '. + {"cliPluginsExtraDirs": ["/opt/homebrew/lib/docker/cli-plugins"]}' ~/.docker/config.json.bak > ~/.docker/config.json
  tags:
    - docker

