---
- name: Ensure Neovim configuration directory exists
  ansible.builtin.file:
    path: "{{ neovim_config_dest }}"
    state: directory
    mode: '0755'
  tags:
    - neovim

- name: Clone Neovim configuration repository from GitHub
  ansible.builtin.git:
    repo: "{{ neovim_config_repo }}"
    dest: "{{ neovim_config_dest }}"
    version: "{{ neovim_config_version }}"
    force: "{{ neovim_config_force }}"
  tags:
    - neovim
